# This is a basic workflow to help you get started with Actions

name: Generate-JSON

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Installs pandas and attackcti modules
      - name: Install requirements
        run: python3 -m pip install pandas attackcti

      # Runs a set of commands using the runners shell
      - name: Generate the latest files
        run: python3 scripts/ossemDM.py
      
      # Commit changes back to the main branch
      - uses: stefanzweifel/git-auto-commit-action@v4
